# Generated by Django 4.2.10 on 2026-01-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('b2b_orders', models.PositiveIntegerField(default=0)),
                ('b2c_orders', models.PositiveIntegerField(default=0)),
                ('aov_b2b', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aov_b2c', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('total_sold', models.PositiveIntegerField(default=0)),
                ('low_stock_alert', models.BooleanField(default=False)),
            ],
        ),
    ]
