# Generated by Django 4.2.10 on 2026-01-11 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short description for listings and search results', max_length=300)),
                ('content', models.TextField(help_text='Full article content (HTML supported)')),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_read_time', models.IntegerField(default=3, help_text='Estimated read time in minutes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on help center homepage')),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular article')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search', max_length=500)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('keywords', models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=255)),
                ('views_count', models.IntegerField(default=0)),
                ('helpful_yes', models.IntegerField(default=0, help_text="Number of 'Yes, this was helpful' votes")),
                ('helpful_no', models.IntegerField(default=0, help_text="Number of 'No' votes")),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Help Article',
                'verbose_name_plural': 'Help Articles',
                'ordering': ['category__order', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('icon', models.CharField(default='help', help_text="Material icon name (e.g., 'inventory_2', 'local_shipping')", max_length=50)),
                ('color', models.CharField(default='#0D7B7F', help_text='Accent color for this category', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on help center homepage')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help Category',
                'verbose_name_plural': 'Help Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticleSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('results_count', models.IntegerField(default=0)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.helparticle')),
            ],
            options={
                'verbose_name': 'Help Search Query',
                'verbose_name_plural': 'Help Search Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='helparticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.helpcategory'),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='referenced_by', to='content.helparticle'),
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['status', '-published_at'], name='content_hel_status_c869f4_idx'),
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['category', 'order'], name='content_hel_categor_a7be62_idx'),
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['-views_count'], name='content_hel_views_c_12230f_idx'),
        ),
    ]
