# Generated by Django 4.2.10 on 2026-01-12 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_category_image'),
        ('content', '0002_helparticle_helpcategory_helparticlesearch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcategory',
            name='category_type',
            field=models.CharField(choices=[('general', 'General'), ('product', 'Product Type'), ('industry', 'Industry'), ('topic', 'Topic')], default='general', help_text='Type of category for filtering', max_length=20),
        ),
        migrations.AddField(
            model_name='helpcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category (leave empty for main category)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='content.helpcategory'),
        ),
        migrations.CreateModel(
            name='HelpCategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this product in the category')),
                ('help_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='content.helpcategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_categories', to='products.product')),
            ],
            options={
                'verbose_name': 'Category Product',
                'verbose_name_plural': 'Category Products',
                'ordering': ['order', '-is_featured'],
                'unique_together': {('help_category', 'product')},
            },
        ),
    ]
