# Generated by Django 4.2.10 on 2026-01-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_subcategories_and_products'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='helpcategoryproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='helpcategoryproduct',
            name='help_category',
        ),
        migrations.RemoveField(
            model_name='helpcategoryproduct',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category__order', 'order'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='footersection',
            options={'ordering': ['order'], 'verbose_name': 'Footer Section', 'verbose_name_plural': 'Footer Sections'},
        ),
        migrations.AlterModelOptions(
            name='helparticle',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Help Article', 'verbose_name_plural': 'Help Articles'},
        ),
        migrations.RemoveIndex(
            model_name='helparticle',
            name='content_hel_status_c869f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='helparticle',
            name='content_hel_views_c_12230f_idx',
        ),
        migrations.RemoveField(
            model_name='footersection',
            name='column',
        ),
        migrations.RemoveField(
            model_name='footersection',
            name='content',
        ),
        migrations.RemoveField(
            model_name='helparticlesearch',
            name='clicked_article',
        ),
        migrations.RemoveField(
            model_name='helpcategory',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='helpcategory',
            name='parent',
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='helpful_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='helparticlesearch',
            name='session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['status', 'is_active'], name='content_hel_status_f5f155_idx'),
        ),
        migrations.DeleteModel(
            name='HelpCategoryProduct',
        ),
    ]
