# Generated by Django 4.2.10 on 2026-01-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('Canada Post', 'Canada Post'), ('UPS', 'UPS'), ('FedEx', 'FedEx')], max_length=50)),
                ('service_type', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('overnight', 'Overnight')], max_length=50)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_kg_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cutoff_time', models.TimeField(blank=True, null=True)),
                ('processing_days', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
