# Generated by Django 4.2.10 on 2026-01-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='max_processing_days',
            field=models.PositiveIntegerField(default=3, help_text='Maximum delivery days'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='min_processing_days',
            field=models.PositiveIntegerField(default=1, help_text='Minimum delivery days'),
        ),
    ]
